In [67]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

##行列積
以下のような行列A、Bを考えます。

　　　　　　　　　　　　$% <![CDATA[
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right] %]]>$

NumPyで表すと次のようになります。





Texコマンドを$$で囲むとTex表示

##【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。

　　　　　　　　　　　　$% <![CDATA[
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right] %]]>$





##やり方
1.   Aの1行目(-1,2,3)とBの1列目(0,0,2)計算
2.   Aの1行目とBの2列目計算　
3.   Aの1行目とBの3列目計算　
4.   Aの2行目(4,-5,6)とBの1列目(0,0,2)計算


9.   Aの3行目(7,8,-9)とBの3列目(1,-8,-1)計算

##計算

|  -1ｘ0 + 2ｘ0 + 3ｘ2　　-1ｘ2 + 2ｘ2 + 3ｘ9　  -1ｘ1 + 2ｘ-8 + 3ｘ-1　　|

|  4ｘ0 + (-5)ｘ0 + 6ｘ2　4ｘ2 + (-5)ｘ2 + 6ｘ9　4ｘ1 + (-5)ｘ-8 + 6ｘ-1　|

|  7ｘ0 + 8ｘ0 + (-9)ｘ2　7ｘ2 + 8ｘ2 + (-9)ｘ9　7ｘ1 + 8ｘ-8 + (-9)ｘ-1　|


##答え

|　6　　 29　　-20　  |

|　12　　52　　-38　  |

|　-18　　-51　　-48　|



##【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください

《3種類の違い》


np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。


今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。


If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred

np.matmul()の場合

In [ ]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

np.dot()の場合

In [ ]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

@演算子の場合

In [ ]:
a_ndarray@b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

##【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

1. 行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる
2. 行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $b_{1, 0}$ を掛け合わせる
3. 行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $b_{2, 0}$ を掛け合わせる
4. それらの値を全て足し合わせる

数式で表すと

　　　　　　　$\sum^{2}_{k=0}a_{0,k}b_{k,0}$


です。


この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [ ]:
n_ndarray = [a_ndarray[0][0]*b_ndarray[0][0] + a_ndarray[0][1]*b_ndarray[1][0] + a_ndarray[0][2]*b_ndarray[2][0]]
n_ndarray

[6]

##【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。

$c_{i,j} = \sum^{2}_{k=0}a_{i,k}b_{k,j}$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。


![代替テキスト](https://t.gyazo.com/teams/diveintocode/129123df5242c9e768513f5e8b5ef24f.png)

In [139]:
def matrix_product(array_1,array_2):
  array_3 = np.zeros((array_1.shape[0], array_2.shape[1])) #[0]で列 [1]で行
  for i in range(array_1.shape[0]):
    for j in range(array_2.shape[1]):
      val = 0
      for k in range(array_1.shape[1]):
        val += array_1[i,k]*array_2[k,j]
        array_3[i,j] = val
  return array_3

matrix_product(a_ndarray,b_ndarray)


array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

###行列積が定義されない組み合わせの行列
次に以下のような例を考えます。

　　　　　$% <![CDATA[
D = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6
    \end{array}
  \right],
  E- = \left[
    \begin{array}{ccc}
       -9 & 8 & 7 \\
      6 & -5 & 4
    \end{array}
  \right] %]]>$

In [43]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

###行列積の定義
行列の（一般的な）積：
行列 $A=(a_{ij}),B=(b_{ij})$に対してその積 AB を
$C=(c_{ij})$ ただし， $c_{ij}=\displaystyle\sum_{k=1}^na_{ik}b_{kj}$
で定義する。ただし，A の列数と B の行数（=n とおく）が一致しているときのみ積AB は定義される。

###結論
行の個数と

列の個数が等しいときに

行と列の内積が定義されます。

引用
https://mathtrain.jp/matrixproduct

##【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [136]:
def matrix_product(array_1,array_2):
  try:
    
    #行と列が等しいか判定
    if array_1.shape[0] != array_2.shape[1]:
      raise Exception

      #行列積の計算
    else:
      array_3 = np.zeros((array_1.shape[0], array_2.shape[1])) #[0]で列 [1]で行
      for i in range(array_1.shape[0]):
        for j in range(array_2.shape[1]):
          val = 0
          for k in range(array_1.shape[1]):
            val += array_1[i,k]*array_2[k,j]
          array_3[i,j] = val
      return array_3
      
  except Exception as e:
    print("[ERROR]行の個数と列の個数が等しくないので積の計算はできません")
    print(type(e))

matrix_product(d_ndarray,e_ndarray)

[ERROR]行の個数と列の個数が等しくないので積の計算はできません
<class 'Exception'>


##【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

np.transpose()の場合

In [137]:
x = d_ndarray.transpose()

matrix_product(x,e_ndarray)

array([[ 33., -28.,   9.],
       [-48.,  41.,  -6.],
       [  9.,  -6.,  45.]])

.Tの場合

In [138]:
y = e_ndarray.T

matrix_product(d_ndarray,y)

array([[ 46.,  -4.],
       [-34.,  73.]])